<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131002110643 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE entry (id INT AUTO_INCREMENT NOT NULL, location_id INT DEFAULT NULL, number VARCHAR(255) NOT NULL, transaction_key VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, next_reservation_at DATETIME NOT NULL, INDEX IDX_2B219D7064D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE location (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE price (id INT AUTO_INCREMENT NOT NULL, location_id INT DEFAULT NULL, period INT NOT NULL, price_amount NUMERIC(16, 6) DEFAULT NULL, priceCurrency VARCHAR(255) NOT NULL, period_from INT DEFAULT NULL, period_to INT DEFAULT NULL, active_from VARCHAR(255) DEFAULT NULL, active_to VARCHAR(255) DEFAULT NULL, active TINYINT(1) NOT NULL, INDEX IDX_CAC822D964D218E (location_id), INDEX IDX_CAC822D97F1C2BDE8435CF4A4B1EFC02 (period_from, period_to, active), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE entry ADD CONSTRAINT FK_2B219D7064D218E FOREIGN KEY (location_id) REFERENCES location (id)");
        $this->addSql("ALTER TABLE price ADD CONSTRAINT FK_CAC822D964D218E FOREIGN KEY (location_id) REFERENCES location (id)");

        $this->addSql("ALTER TABLE entry ADD price_amount NUMERIC(16, 6) DEFAULT NULL, ADD price_currency VARCHAR(255) NOT NULL");
        $this->addSql("CREATE INDEX IDX_2B219D7096901F547B00651C ON entry (number, status)");
        $this->addSql("CREATE INDEX IDX_2B219D70C9CDC1E2 ON entry (next_reservation_at)");
        $this->addSql("CREATE INDEX IDX_5E9E89CB5E237E06 ON location (name)");
        $this->addSql("CREATE INDEX IDX_2B219D707B00651C ON entry (status)");

        $this->addSql("ALTER TABLE entry CHANGE transaction_key transaction_key VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE entry");
        $this->addSql("DROP TABLE location");
        $this->addSql("DROP TABLE price");
    }
}
